name: stripe
version: 4.13.2
description: A simple Stripe API wrapper, that is meant to be used on the server.
homepage: https://github.com/enyo/stripe-dart
documentation: https://github.com/enyo/stripe-dart/blob/main/README.md
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  crypto: ^3.0.0
  json_annotation: ^4.9.0
  meta: ^1.16.0
  logging: ^1.3.0
  dio: ^5.9.0
dev_dependencies:
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  test: ^1.26.0
  mocktail: ^1.0.4
  lints: ^6.0.0
